namespace WinBoard.Core;

/// <summary>One emoji with bilingual (FR/EN) search keywords.</summary>
public sealed record EmojiItem(string Glyph, string Keywords);

/// <summary>Gboard-style emoji group. <see cref="Items"/> is empty for virtual tabs (récents, recherche).</summary>
public sealed record EmojiCategory(string Id, string Label, string Icon, IReadOnlyList<EmojiItem> Items);

/// <summary>
/// Offline emoji catalog for the WinBoard panel. No network, no glyph download.
/// Search matches folded keywords (accents stripped) so « coeur » finds ❤️.
/// </summary>
public static class EmojiCatalog
{
    public const string RecentsId = "recents";
    public const string SearchId = "search";
    public const int RecentLimit = 24;

    public static IReadOnlyList<EmojiCategory> Categories { get; } = BuildCategories();

    public static IReadOnlyList<EmojiItem> All { get; } =
        Categories.SelectMany(c => c.Items).DistinctBy(e => e.Glyph).ToArray();

    public static IReadOnlyList<EmojiItem> Search(string query)
    {
        string folded = new(TextFolding.ToLetters(query));
        if (folded.Length == 0)
        {
            return [];
        }

        return All.Where(item => KeywordFold(item.Keywords).Contains(folded, StringComparison.Ordinal)).ToArray();
    }

    /// <summary>Moves <paramref name="glyph"/> to the front of the recent list (max <see cref="RecentLimit"/>).</summary>
    public static List<string> PushRecent(IEnumerable<string>? current, string glyph, int max = RecentLimit)
    {
        var result = new List<string>(max);
        if (!string.IsNullOrWhiteSpace(glyph))
        {
            result.Add(glyph);
        }

        if (current is not null)
        {
            foreach (string item in current)
            {
                if (string.IsNullOrWhiteSpace(item) || item == glyph)
                {
                    continue;
                }

                result.Add(item);
                if (result.Count >= max)
                {
                    break;
                }
            }
        }

        return result;
    }

    public static IReadOnlyList<EmojiItem> ResolveRecent(IEnumerable<string>? glyphs)
    {
        if (glyphs is null)
        {
            return [];
        }

        var map = All.ToDictionary(e => e.Glyph, StringComparer.Ordinal);
        var list = new List<EmojiItem>();
        foreach (string glyph in glyphs)
        {
            if (map.TryGetValue(glyph, out EmojiItem? item))
            {
                list.Add(item);
            }
            else if (!string.IsNullOrWhiteSpace(glyph))
            {
                list.Add(new EmojiItem(glyph, string.Empty));
            }
        }

        return list;
    }

    private static string KeywordFold(string keywords) => new(TextFolding.ToLetters(keywords));

    private static EmojiItem E(string glyph, string keywords) => new(glyph, keywords);

    private static IReadOnlyList<EmojiCategory> BuildCategories() =>
    [
        new("smileys", "Smileys", "😀", Smileys()),
        new("people", "Personnes", "👋", People()),
        new("nature", "Nature", "🌿", Nature()),
        new("food", "Nourriture", "🍔", Food()),
        new("activities", "Activités", "⚽", Activities()),
        new("travel", "Voyages", "✈️", Travel()),
        new("objects", "Objets", "💡", Objects()),
        new("symbols", "Symboles", "🔣", Symbols()),
        new("flags", "Drapeaux", "🚩", Flags()),
    ];

    private static EmojiItem[] Smileys() =>
    [
        E("😀", "grin smile happy sourire joyeux"),
        E("😃", "smile happy sourire ouvert"),
        E("😄", "smile eyes sourire yeux"),
        E("😁", "grin beam sourire dents"),
        E("😆", "laugh lol mdr rire"),
        E("😅", "sweat nervous sueur ouf"),
        E("😂", "joy tears mdr larmes rire"),
        E("🤣", "rofl rolling mdr par terre"),
        E("😊", "blush smile content"),
        E("😇", "angel halo ange"),
        E("🙂", "slight smile leger sourire"),
        E("😉", "wink clin oeil"),
        E("😍", "heart eyes amour coeur"),
        E("🥰", "smiling hearts amour"),
        E("😘", "kiss bisou"),
        E("😗", "kiss bisou"),
        E("😚", "kiss closed bisou"),
        E("😋", "yum delicious savoureux"),
        E("😛", "tongue langue"),
        E("😜", "wink tongue langue clin"),
        E("🤪", "zany fou"),
        E("😝", "tongue squint langue"),
        E("🤑", "money greedy argent"),
        E("🤗", "hug calin"),
        E("🤭", "oops oops hand bouche"),
        E("🤫", "shush silence chut"),
        E("🤔", "think penser hmm"),
        E("🤐", "zipper mute zip"),
        E("🤨", "raised eyebrow sceptique"),
        E("😐", "neutral neutre"),
        E("😑", "expressionless"),
        E("😶", "silent sans bouche"),
        E("😏", "smirk narquois"),
        E("😒", "unamused ennuye"),
        E("🙄", "eyeroll yeux"),
        E("😬", "grimace"),
        E("😌", "relieved ouf soulage"),
        E("😔", "pensive triste"),
        E("😪", "sleepy sommeil"),
        E("🤤", "drool bave"),
        E("😴", "sleep zzz dormir"),
        E("😷", "mask sick masque malade"),
        E("🤒", "thermometer fievre"),
        E("🤕", "bandage blessure"),
        E("🤢", "nauseated nausee"),
        E("🤮", "vomit vomir"),
        E("🥵", "hot chaud"),
        E("🥶", "cold froid"),
        E("🥴", "woozy etourdi"),
        E("😵", "dizzy ko"),
        E("🤯", "exploding mind blown"),
        E("🤠", "cowboy"),
        E("🥳", "party fete"),
        E("😎", "cool sunglasses lunettes"),
        E("🤓", "nerd lunettes"),
        E("🧐", "monocle"),
        E("😕", "confused confus"),
        E("😟", "worried inquiet"),
        E("🙁", "frown triste"),
        E("☹️", "frown triste"),
        E("😮", "open surprise"),
        E("😯", "hushed surprise"),
        E("😲", "astonished etonne"),
        E("😳", "flushed gene"),
        E("🥺", "pleading please pitie"),
        E("😢", "cry larmes triste"),
        E("😭", "sob pleurer"),
        E("😱", "scream scream peur"),
        E("😖", "confounded"),
        E("😣", "persevere"),
        E("😞", "disappointed decu"),
        E("😓", "downcast sweat"),
        E("😩", "weary las"),
        E("😫", "tired fatigue"),
        E("🥱", "yawn baillement"),
        E("😤", "triumph steam"),
        E("😡", "angry colere"),
        E("😠", "angry fache"),
        E("🤬", "cursing insulte"),
        E("😈", "smiling devil diable"),
        E("👿", "angry devil diable"),
        E("💀", "skull mort tete"),
        E("☠️", "skull crossbones pirate"),
        E("💩", "poop caca"),
        E("🤡", "clown"),
        E("👻", "ghost fantome"),
        E("👽", "alien"),
        E("👾", "invader space"),
        E("🤖", "robot"),
        E("🎃", "pumpkin halloween"),
        E("😺", "cat smile chat"),
        E("😹", "cat joy chat rire"),
        E("😻", "cat heart chat amour"),
        E("🙈", "see monkey singe"),
        E("🙉", "hear monkey singe"),
        E("🙊", "speak monkey singe"),
        E("💋", "kiss mark bisou levres"),
        E("💌", "love letter lettre amour"),
        E("💘", "cupid coeur fleche"),
        E("💝", "heart ribbon coeur"),
        E("💖", "sparkling heart coeur"),
        E("💗", "growing heart coeur"),
        E("💓", "beating heart coeur"),
        E("💞", "revolving hearts coeurs"),
        E("💕", "two hearts coeurs"),
        E("💟", "heart decoration coeur"),
        E("❣️", "heart exclamation coeur"),
        E("💔", "broken heart coeur brise"),
        E("❤️", "red heart coeur rouge love amour"),
        E("🧡", "orange heart coeur"),
        E("💛", "yellow heart coeur"),
        E("💚", "green heart coeur"),
        E("💙", "blue heart coeur"),
        E("💜", "purple heart coeur"),
        E("🖤", "black heart coeur"),
        E("🤍", "white heart coeur"),
        E("💯", "hundred 100"),
        E("💢", "anger colere"),
        E("💥", "collision boom"),
        E("💫", "dizzy etoile"),
        E("💦", "sweat drops sueur"),
        E("💨", "dash vent"),
        E("🕳️", "hole trou"),
        E("💬", "speech bubble bulle"),
        E("💤", "zzz sleep"),
    ];

    private static EmojiItem[] People() =>
    [
        E("👋", "wave salut bye hello"),
        E("🤚", "raised back hand"),
        E("🖐️", "hand fingers"),
        E("✋", "raised hand stop"),
        E("👌", "ok"),
        E("🤌", "pinched fingers italien"),
        E("✌️", "victory paix"),
        E("🤞", "crossed fingers chance"),
        E("🤟", "love you"),
        E("🤘", "horns rock"),
        E("🤙", "call me tel"),
        E("👈", "point left gauche"),
        E("👉", "point right droite"),
        E("👆", "point up haut"),
        E("👇", "point down bas"),
        E("☝️", "index up"),
        E("👍", "thumbs up oui like top"),
        E("👎", "thumbs down non"),
        E("✊", "fist poing"),
        E("👊", "punch poing"),
        E("🤛", "left fist"),
        E("🤜", "right fist"),
        E("👏", "clap bravo"),
        E("🙌", "hooray hands"),
        E("👐", "open hands"),
        E("🤲", "palms"),
        E("🤝", "handshake accord"),
        E("🙏", "pray please merci please"),
        E("✍️", "writing ecrire"),
        E("💅", "nails vernis"),
        E("🤳", "selfie"),
        E("💪", "muscle biceps fort"),
        E("🦾", "mechanical arm"),
        E("🦵", "leg jambe"),
        E("🦶", "foot pied"),
        E("👂", "ear oreille"),
        E("👃", "nose nez"),
        E("🧠", "brain cerveau"),
        E("👀", "eyes yeux"),
        E("👁️", "eye oeil"),
        E("👅", "tongue langue"),
        E("👄", "mouth bouche"),
        E("👶", "baby bebe"),
        E("🧒", "child enfant"),
        E("👦", "boy garcon"),
        E("👧", "girl fille"),
        E("🧑", "person personne"),
        E("👱", "blond"),
        E("👨", "man homme"),
        E("👩", "woman femme"),
        E("🧔", "beard barbe"),
        E("🧓", "older age"),
        E("👴", "old man papy"),
        E("👵", "old woman mamie"),
        E("🙍", "frowning"),
        E("🙎", "pouting"),
        E("🙅", "no gesture"),
        E("🙆", "ok gesture"),
        E("💁", "sassy tip"),
        E("🙋", "raise hand"),
        E("🧏", "deaf"),
        E("🙇", "bow salut"),
        E("🤦", "facepalm"),
        E("🤷", "shrug je sais pas"),
        E("👨‍⚕️", "man doctor medecin"),
        E("👩‍⚕️", "woman doctor medecin"),
        E("👨‍🏫", "man teacher prof"),
        E("👩‍🏫", "woman teacher prof"),
        E("👨‍💻", "man technologist dev"),
        E("👩‍💻", "woman technologist dev"),
        E("👮", "police"),
        E("🕵️", "detective"),
        E("💂", "guard garde"),
        E("🥷", "ninja"),
        E("👷", "construction worker"),
        E("🤴", "prince"),
        E("👸", "princess princesse"),
        E("👳", "turban"),
        E("👲", "skullcap"),
        E("🧕", "headscarf hijab"),
        E("🤵", "tuxedo"),
        E("👰", "bride mariee"),
        E("🤰", "pregnant enceinte"),
        E("🤱", "breastfeeding"),
        E("👼", "baby angel ange"),
        E("🎅", "santa pere noel"),
        E("🤶", "mrs claus"),
        E("🦸", "superhero super heros"),
        E("🦹", "supervillain mechant"),
        E("🧙", "mage wizard"),
        E("🧚", "fairy fee"),
        E("🧛", "vampire"),
        E("🧜", "mermaid sirene"),
        E("🧝", "elf elfe"),
        E("🧞", "genie"),
        E("🧟", "zombie"),
        E("💆", "massage"),
        E("💇", "haircut coiffure"),
        E("🚶", "walk marche"),
        E("🧍", "stand debout"),
        E("🧎", "kneel"),
        E("🏃", "run course"),
        E("💃", "dance danse"),
        E("🕺", "man dancing"),
        E("🕴️", "levitate"),
        E("👯", "dancers"),
        E("🧖", "sauna"),
        E("🧗", "climb escalade"),
        E("🏇", "horse racing"),
        E("⛷️", "ski"),
        E("🏂", "snowboard"),
        E("🏌️", "golf"),
        E("🏄", "surf"),
        E("🚣", "row rowing"),
        E("🏊", "swim nage"),
        E("⛹️", "ball bounce"),
        E("🏋️", "weights muscu"),
        E("🚴", "bike velo"),
        E("🚵", "mountain bike"),
        E("🤸", "cartwheel"),
        E("🤼", "wrestle"),
        E("🤽", "water polo"),
        E("🤾", "handball"),
        E("🤹", "juggle jongle"),
        E("🧘", "lotus yoga"),
        E("🛀", "bath bain"),
        E("🛌", "bed lit"),
        E("👭", "women holding hands"),
        E("👫", "couple holding"),
        E("👬", "men holding hands"),
        E("💏", "kiss couple bisou"),
        E("💑", "couple heart"),
        E("👨‍👩‍👧", "family famille"),
        E("👤", "bust silhouette"),
        E("👥", "busts silhouettes"),
        E("🫂", "people hugging calin"),
        E("👣", "footprints traces"),
    ];

    private static EmojiItem[] Nature() =>
    [
        E("🐶", "dog chien"),
        E("🐱", "cat chat"),
        E("🐭", "mouse souris"),
        E("🐹", "hamster"),
        E("🐰", "rabbit lapin"),
        E("🦊", "fox renard"),
        E("🐻", "bear ours"),
        E("🐼", "panda"),
        E("🐨", "koala"),
        E("🐯", "tiger tigre"),
        E("🦁", "lion"),
        E("🐮", "cow vache"),
        E("🐷", "pig cochon"),
        E("🐸", "frog grenouille"),
        E("🐵", "monkey singe"),
        E("🙈", "see monkey"),
        E("🐔", "chicken poule"),
        E("🐧", "penguin pingouin"),
        E("🐦", "bird oiseau"),
        E("🐤", "chick poussin"),
        E("🦆", "duck canard"),
        E("🦅", "eagle aigle"),
        E("🦉", "owl hibou"),
        E("🦇", "bat chauve souris"),
        E("🐺", "wolf loup"),
        E("🐗", "boar sanglier"),
        E("🐴", "horse cheval"),
        E("🦄", "unicorn licorne"),
        E("🐝", "bee abeille"),
        E("🪱", "worm ver"),
        E("🐛", "bug chenille"),
        E("🦋", "butterfly papillon"),
        E("🐌", "snail escargot"),
        E("🐞", "ladybug coccinelle"),
        E("🐜", "ant fourmi"),
        E("🪰", "fly mouche"),
        E("🪲", "beetle"),
        E("🪳", "cockroach cafard"),
        E("🦟", "mosquito moustique"),
        E("🦗", "cricket"),
        E("🕷️", "spider araignee"),
        E("🦂", "scorpion"),
        E("🐢", "turtle tortue"),
        E("🐍", "snake serpent"),
        E("🦎", "lizard lezard"),
        E("🦖", "t-rex dinosaure"),
        E("🦕", "sauropod dinosaure"),
        E("🐙", "octopus poulpe"),
        E("🦑", "squid calamar"),
        E("🦐", "shrimp crevette"),
        E("🦞", "lobster homard"),
        E("🦀", "crab crabe"),
        E("🐡", "blowfish"),
        E("🐠", "tropical fish poisson"),
        E("🐟", "fish poisson"),
        E("🐬", "dolphin dauphin"),
        E("🐳", "whale baleine"),
        E("🐋", "whale baleine"),
        E("🦈", "shark requin"),
        E("🐊", "crocodile"),
        E("🐅", "tiger tigre"),
        E("🐆", "leopard"),
        E("🦓", "zebra zebre"),
        E("🦍", "gorilla gorille"),
        E("🦧", "orangutan"),
        E("🐘", "elephant"),
        E("🦛", "hippo hippopotame"),
        E("🦏", "rhino rhino"),
        E("🐪", "camel chameau"),
        E("🐫", "camel two"),
        E("🦒", "giraffe girafe"),
        E("🦘", "kangaroo kangourou"),
        E("🦬", "bison"),
        E("🐃", "water buffalo"),
        E("🐂", "ox boeuf"),
        E("🐄", "cow vache"),
        E("🐎", "racehorse cheval"),
        E("🐖", "pig cochon"),
        E("🐏", "ram belier"),
        E("🐑", "ewe mouton"),
        E("🦙", "llama lama"),
        E("🐐", "goat chevre"),
        E("🦌", "deer cerf"),
        E("🐕", "dog chien"),
        E("🐩", "poodle caniche"),
        E("🦮", "guide dog"),
        E("🐈", "cat chat"),
        E("🐓", "rooster coq"),
        E("🦃", "turkey dinde"),
        E("🦚", "peacock paon"),
        E("🦜", "parrot perroquet"),
        E("🦢", "swan cygne"),
        E("🦩", "flamingo"),
        E("🕊️", "dove colombe paix"),
        E("🐇", "rabbit lapin"),
        E("🦝", "raccoon raton"),
        E("🦨", "skunk mouffette"),
        E("🦡", "badger blaireau"),
        E("🦫", "beaver castor"),
        E("🦦", "otter loutre"),
        E("🦥", "sloth paresseux"),
        E("🐁", "mouse souris"),
        E("🐀", "rat"),
        E("🐿️", "chipmunk"),
        E("🦔", "hedgehog herisson"),
        E("🐾", "paws pattes"),
        E("🐉", "dragon"),
        E("🐲", "dragon face"),
        E("🌵", "cactus"),
        E("🎄", "christmas tree sapin"),
        E("🌲", "evergreen sapin"),
        E("🌳", "deciduous arbre"),
        E("🌴", "palm palma palme"),
        E("🪵", "wood bois"),
        E("🌱", "seedling pousse"),
        E("🌿", "herb herbe plante"),
        E("☘️", "shamrock trefle"),
        E("🍀", "clover trefle quatre"),
        E("🎍", "bamboo bambou"),
        E("🪴", "potted plant plante"),
        E("🎋", "tanabata"),
        E("🍃", "leaf vent feuille"),
        E("🍂", "fallen leaf automne"),
        E("🍁", "maple erable"),
        E("🍄", "mushroom champignon"),
        E("🐚", "shell coquillage"),
        E("🪸", "coral corail"),
        E("🪨", "rock rocher"),
        E("🌾", "sheaf rice ble"),
        E("💐", "bouquet fleurs"),
        E("🌷", "tulip tulipe"),
        E("🌹", "rose"),
        E("🥀", "wilted fanee"),
        E("🌺", "hibiscus"),
        E("🌸", "cherry blossom sakura cerisier"),
        E("🌼", "blossom fleur"),
        E("🌻", "sunflower tournesol"),
        E("🌞", "sun face soleil"),
        E("🌝", "full moon face"),
        E("🌛", "first quarter moon"),
        E("🌜", "last quarter moon"),
        E("🌚", "new moon face"),
        E("🌕", "full moon lune"),
        E("🌖", "waning moon"),
        E("🌗", "last quarter"),
        E("🌘", "waning crescent"),
        E("🌑", "new moon"),
        E("🌒", "waxing crescent"),
        E("🌓", "first quarter"),
        E("🌔", "waxing gibbous"),
        E("🌙", "crescent moon lune"),
        E("🌎", "earth americas terre"),
        E("🌍", "earth africa terre"),
        E("🌏", "earth asia terre"),
        E("🪐", "saturn planete"),
        E("💫", "dizzy etoile"),
        E("⭐", "star etoile"),
        E("🌟", "glowing star etoile"),
        E("✨", "sparkles etincelles"),
        E("⚡", "lightning eclair"),
        E("☄️", "comet comete"),
        E("💥", "boom"),
        E("🔥", "fire feu"),
        E("🌪️", "tornado"),
        E("🌈", "rainbow arc en ciel"),
        E("☀️", "sun soleil"),
        E("🌤️", "sun cloud"),
        E("⛅", "cloud sun nuage"),
        E("🌥️", "cloud sun"),
        E("☁️", "cloud nuage"),
        E("🌦️", "sun rain"),
        E("🌧️", "cloud rain pluie"),
        E("⛈️", "storm orage"),
        E("🌩️", "cloud lightning"),
        E("🌨️", "cloud snow neige"),
        E("❄️", "snowflake flocon"),
        E("☃️", "snowman bonhomme neige"),
        E("⛄", "snowman"),
        E("🌬️", "wind vent"),
        E("💨", "dash"),
        E("💧", "droplet goutte"),
        E("💦", "sweat drops"),
        E("☔", "umbrella rain parapluie"),
        E("☂️", "umbrella parapluie"),
        E("🌊", "wave vague ocean mer"),
        E("🌫️", "fog brouillard"),
    ];

    private static EmojiItem[] Food() =>
    [
        E("🍏", "green apple pomme"),
        E("🍎", "red apple pomme"),
        E("🍐", "pear poire"),
        E("🍊", "orange tangerine"),
        E("🍋", "lemon citron"),
        E("🍌", "banana banane"),
        E("🍉", "watermelon pasteque"),
        E("🍇", "grapes raisin"),
        E("🍓", "strawberry fraise"),
        E("🫐", "blueberries myrtilles"),
        E("🍈", "melon"),
        E("🍒", "cherries cerises"),
        E("🍑", "peach peche"),
        E("🥭", "mango mangue"),
        E("🍍", "pineapple ananas"),
        E("🥥", "coconut coco"),
        E("🥝", "kiwi"),
        E("🍅", "tomato tomate"),
        E("🍆", "eggplant aubergine"),
        E("🥑", "avocado avocat"),
        E("🥦", "broccoli"),
        E("🥬", "leafy green salade"),
        E("🥒", "cucumber concombre"),
        E("🌶️", "pepper piment"),
        E("🫑", "bell pepper poivron"),
        E("🌽", "corn mais"),
        E("🥕", "carrot carotte"),
        E("🫒", "olive"),
        E("🧄", "garlic ail"),
        E("🧅", "onion oignon"),
        E("🥔", "potato pomme terre"),
        E("🍠", "sweet potato"),
        E("🥐", "croissant"),
        E("🥯", "bagel"),
        E("🍞", "bread pain"),
        E("🥖", "baguette pain"),
        E("🥨", "pretzel"),
        E("🧀", "cheese fromage"),
        E("🥚", "egg oeuf"),
        E("🍳", "cooking oeuf plat"),
        E("🧈", "butter beurre"),
        E("🥞", "pancakes crepes"),
        E("🧇", "waffle gaufre"),
        E("🥓", "bacon"),
        E("🥩", "steak viande"),
        E("🍗", "poultry chicken poulet"),
        E("🍖", "meat os"),
        E("🌭", "hotdog"),
        E("🍔", "hamburger burger"),
        E("🍟", "fries frites"),
        E("🍕", "pizza"),
        E("🫓", "flatbread"),
        E("🥪", "sandwich"),
        E("🥙", "stuffed pita"),
        E("🧆", "falafel"),
        E("🌮", "taco"),
        E("🌯", "burrito"),
        E("🫔", "tamale"),
        E("🥗", "salad salade"),
        E("🥘", "paella"),
        E("🫕", "fondue"),
        E("🥫", "canned"),
        E("🍝", "spaghetti pasta pates"),
        E("🍜", "ramen nouilles"),
        E("🍲", "stew pot"),
        E("🍛", "curry"),
        E("🍣", "sushi"),
        E("🍱", "bento"),
        E("🥟", "dumpling ravioli"),
        E("🦪", "oyster huitre"),
        E("🍤", "fried shrimp"),
        E("🍙", "rice ball"),
        E("🍚", "rice riz"),
        E("🍘", "rice cracker"),
        E("🍥", "fish cake"),
        E("🥠", "fortune cookie"),
        E("🥮", "moon cake"),
        E("🍢", "oden"),
        E("🍡", "dango"),
        E("🍧", "shaved ice"),
        E("🍨", "ice cream glace"),
        E("🍦", "soft ice cream"),
        E("🥧", "pie tarte"),
        E("🧁", "cupcake muffin"),
        E("🍰", "cake gateau"),
        E("🎂", "birthday cake anniversaire"),
        E("🍮", "custard flan"),
        E("🍭", "lollipop sucette"),
        E("🍬", "candy bonbon"),
        E("🍫", "chocolate chocolat"),
        E("🍿", "popcorn"),
        E("🍩", "doughnut donut"),
        E("🍪", "cookie biscuit"),
        E("🌰", "chestnut chataigne"),
        E("🥜", "peanuts cacahuete"),
        E("🍯", "honey miel"),
        E("🥛", "milk lait"),
        E("🍼", "baby bottle biberon"),
        E("🫖", "teapot theiere"),
        E("☕", "coffee cafe"),
        E("🍵", "tea the"),
        E("🧃", "juice jus"),
        E("🥤", "cup straw soda"),
        E("🧋", "bubble tea"),
        E("🍶", "sake"),
        E("🍺", "beer biere"),
        E("🍻", "beers sante"),
        E("🥂", "champagne toast"),
        E("🍷", "wine vin"),
        E("🥃", "tumbler whisky"),
        E("🍸", "cocktail"),
        E("🍹", "tropical drink"),
        E("🧉", "mate"),
        E("🍾", "bottle pop champagne"),
        E("🧊", "ice glacon"),
        E("🥄", "spoon cuillere"),
        E("🍴", "fork knife couvert"),
        E("🍽️", "plate couvert"),
        E("🥣", "bowl bol"),
        E("🥡", "takeout"),
        E("🥢", "chopsticks baguettes"),
        E("🧂", "salt sel"),
    ];

    private static EmojiItem[] Activities() =>
    [
        E("⚽", "soccer football"),
        E("🏀", "basketball basket"),
        E("🏈", "football american"),
        E("⚾", "baseball"),
        E("🥎", "softball"),
        E("🎾", "tennis"),
        E("🏐", "volleyball"),
        E("🏉", "rugby"),
        E("🥏", "flying disc frisbee"),
        E("🎱", "billiards pool 8ball"),
        E("🪀", "yo-yo"),
        E("🏓", "ping pong"),
        E("🏸", "badminton"),
        E("🏒", "ice hockey"),
        E("🏑", "field hockey"),
        E("🥍", "lacrosse"),
        E("🏏", "cricket"),
        E("🪃", "boomerang"),
        E("🥅", "goal filet"),
        E("⛳", "golf flag"),
        E("🪁", "kite cerf volant"),
        E("🏹", "bow arrow tir"),
        E("🎣", "fishing peche"),
        E("🤿", "diving plongee"),
        E("🥊", "boxing boxe"),
        E("🥋", "martial arts judo"),
        E("🎽", "running shirt"),
        E("🛹", "skateboard skate"),
        E("🛼", "roller skate"),
        E("🛷", "sled luge"),
        E("⛸️", "ice skate patin"),
        E("🥌", "curling"),
        E("🎿", "ski"),
        E("⛷️", "skier"),
        E("🏂", "snowboard"),
        E("🪂", "parachute"),
        E("🏋️", "weights"),
        E("🤼", "wrestling"),
        E("🤸", "gymnastics gym"),
        E("🤺", "fencing escrime"),
        E("⛹️", "basket bounce"),
        E("🤾", "handball"),
        E("🏌️", "golf swing"),
        E("🏇", "horse race turf"),
        E("🧘", "yoga meditation"),
        E("🏄", "surf"),
        E("🏊", "swim natation"),
        E("🤽", "water polo"),
        E("🚣", "row boat"),
        E("🧗", "climb"),
        E("🚵", "mtb vtt"),
        E("🚴", "cycling velo"),
        E("🏆", "trophy trophee"),
        E("🥇", "gold medal or"),
        E("🥈", "silver medal argent"),
        E("🥉", "bronze medal"),
        E("🏅", "sports medal medaille"),
        E("🎖️", "military medal"),
        E("🏵️", "rosette"),
        E("🎗️", "reminder ribbon"),
        E("🎫", "ticket billet"),
        E("🎟️", "admission tickets"),
        E("🎪", "circus cirque"),
        E("🤹", "juggle"),
        E("🎭", "performing arts theatre"),
        E("🩰", "ballet"),
        E("🎨", "art palette peinture"),
        E("🎬", "clapper cinema"),
        E("🎤", "microphone micro"),
        E("🎧", "headphone casque"),
        E("🎼", "score partition"),
        E("🎹", "piano keyboard"),
        E("🥁", "drum batterie"),
        E("🪘", "long drum"),
        E("🎷", "saxophone"),
        E("🎺", "trumpet trompette"),
        E("🪗", "accordion accordeon"),
        E("🎸", "guitar guitare"),
        E("🪕", "banjo"),
        E("🎻", "violin violon"),
        E("🎲", "dice de"),
        E("♟️", "chess pion"),
        E("🎯", "bullseye cible"),
        E("🎳", "bowling"),
        E("🎮", "video game jeu"),
        E("🎰", "slot machine"),
        E("🧩", "puzzle"),
    ];

    private static EmojiItem[] Travel() =>
    [
        E("🚗", "car voiture"),
        E("🚕", "taxi"),
        E("🚙", "suv"),
        E("🚌", "bus"),
        E("🚎", "trolleybus"),
        E("🏎️", "race car formule"),
        E("🚓", "police car"),
        E("🚑", "ambulance"),
        E("🚒", "fire engine pompier"),
        E("🚐", "minibus van"),
        E("🛻", "pickup"),
        E("🚚", "truck camion"),
        E("🚛", "articulated lorry"),
        E("🚜", "tractor tracteur"),
        E("🦯", "white cane"),
        E("🦽", "manual wheelchair"),
        E("🦼", "motorized wheelchair"),
        E("🛴", "scooter trottinette"),
        E("🚲", "bicycle velo"),
        E("🛵", "motor scooter"),
        E("🏍️", "motorcycle moto"),
        E("🛺", "auto rickshaw"),
        E("🚨", "siren gyro"),
        E("🚔", "oncoming police"),
        E("🚍", "oncoming bus"),
        E("🚘", "oncoming car"),
        E("🚖", "oncoming taxi"),
        E("🚡", "cable car"),
        E("🚠", "mountain cableway"),
        E("🚟", "suspension railway"),
        E("🚃", "railway car"),
        E("🚋", "tram"),
        E("🚞", "mountain railway"),
        E("🚝", "monorail"),
        E("🚄", "highspeed train tgv"),
        E("🚅", "bullet train shinkansen"),
        E("🚈", "light rail"),
        E("🚂", "locomotive train"),
        E("🚆", "train"),
        E("🚇", "metro"),
        E("🚊", "tram"),
        E("🚉", "station gare"),
        E("✈️", "airplane avion"),
        E("🛫", "departure decollage"),
        E("🛬", "arrival atterrissage"),
        E("🛩️", "small airplane"),
        E("💺", "seat siege"),
        E("🛰️", "satellite"),
        E("🚀", "rocket fusee"),
        E("🛸", "flying saucer ovni"),
        E("🚁", "helicopter helicoptere"),
        E("🛶", "canoe"),
        E("⛵", "sailboat voilier"),
        E("🚤", "speedboat"),
        E("🛥️", "motor boat"),
        E("🛳️", "passenger ship paquebot"),
        E("⛴️", "ferry ferry"),
        E("🚢", "ship bateau"),
        E("⚓", "anchor ancre"),
        E("🪝", "hook crochet"),
        E("⛽", "fuel pompe essence"),
        E("🚧", "construction travaux"),
        E("🚦", "traffic light feu"),
        E("🚥", "horizontal traffic"),
        E("🚏", "bus stop arret"),
        E("🗺️", "world map carte"),
        E("🗿", "moai"),
        E("🗽", "statue liberty"),
        E("🗼", "tokyo tower"),
        E("🏰", "castle chateau"),
        E("🏯", "japanese castle"),
        E("🏟️", "stadium stade"),
        E("🎡", "ferris wheel grande roue"),
        E("🎢", "roller coaster"),
        E("🎠", "carousel manege"),
        E("⛲", "fountain fontaine"),
        E("⛱️", "umbrella beach"),
        E("🏖️", "beach plage"),
        E("🏝️", "desert island ile"),
        E("🏜️", "desert"),
        E("🌋", "volcano volcan"),
        E("⛰️", "mountain montagne"),
        E("🏔️", "snow mountain"),
        E("🗻", "mount fuji"),
        E("🏕️", "camping"),
        E("⛺", "tent tente"),
        E("🛖", "hut cabane"),
        E("🏠", "house maison"),
        E("🏡", "house garden"),
        E("🏘️", "houses"),
        E("🏚️", "derelict house"),
        E("🏗️", "building construction"),
        E("🏭", "factory usine"),
        E("🏢", "office immeuble"),
        E("🏬", "department store"),
        E("🏣", "japanese post"),
        E("🏤", "post office poste"),
        E("🏥", "hospital hopital"),
        E("🏦", "bank banque"),
        E("🏨", "hotel"),
        E("🏪", "convenience store"),
        E("🏫", "school ecole"),
        E("🏩", "love hotel"),
        E("💒", "wedding mariage"),
        E("🏛️", "classical building"),
        E("⛪", "church eglise"),
        E("🕌", "mosque mosquee"),
        E("🕍", "synagogue"),
        E("🛕", "hindu temple"),
        E("🕋", "kaaba"),
        E("⛩️", "shinto shrine"),
        E("🛤️", "railway track"),
        E("🛣️", "motorway autoroute"),
        E("🗾", "map japan"),
        E("🎑", "moon viewing"),
        E("🏞️", "national park parc"),
        E("🌅", "sunrise lever soleil"),
        E("🌄", "sunrise mountains"),
        E("🌠", "shooting star etoile filante"),
        E("🎇", "sparkler"),
        E("🎆", "fireworks feu artifice"),
        E("🌇", "sunset coucher"),
        E("🌆", "city dusk"),
        E("🏙️", "cityscape ville"),
        E("🌃", "night stars nuit"),
        E("🌌", "milky way voie lactee"),
        E("🌉", "bridge night pont"),
        E("🌁", "foggy"),
    ];

    private static EmojiItem[] Objects() =>
    [
        E("⌚", "watch montre"),
        E("📱", "phone mobile tel"),
        E("📲", "phone arrow"),
        E("💻", "laptop ordi"),
        E("⌨️", "keyboard clavier"),
        E("🖥️", "desktop ordinateur"),
        E("🖨️", "printer imprimante"),
        E("🖱️", "mouse souris"),
        E("🖲️", "trackball"),
        E("🕹️", "joystick"),
        E("🗜️", "clamp"),
        E("💽", "minidisc"),
        E("💾", "floppy diskette"),
        E("💿", "cd"),
        E("📀", "dvd"),
        E("📼", "vhs"),
        E("📷", "camera photo"),
        E("📸", "camera flash"),
        E("📹", "video camera"),
        E("🎥", "movie camera"),
        E("📽️", "film projector"),
        E("🎞️", "film frames"),
        E("📞", "telephone receiver"),
        E("☎️", "telephone"),
        E("📟", "pager"),
        E("📠", "fax"),
        E("📺", "tv tele"),
        E("📻", "radio"),
        E("🎙️", "studio microphone"),
        E("🎚️", "level slider"),
        E("🎛️", "control knobs"),
        E("🧭", "compass boussole"),
        E("⏱️", "stopwatch chrono"),
        E("⏲️", "timer"),
        E("⏰", "alarm clock reveil"),
        E("🕰️", "mantelpiece clock"),
        E("⌛", "hourglass"),
        E("⏳", "hourglass flowing"),
        E("📡", "satellite antenna"),
        E("🔋", "battery pile"),
        E("🔌", "plug prise"),
        E("💡", "bulb idee lampe"),
        E("🔦", "flashlight lampe"),
        E("🕯️", "candle bougie"),
        E("🪔", "diya lamp"),
        E("🧯", "fire extinguisher"),
        E("🛢️", "oil drum"),
        E("💸", "money wings argent"),
        E("💵", "dollar"),
        E("💴", "yen"),
        E("💶", "euro"),
        E("💷", "pound livre"),
        E("🪙", "coin piece"),
        E("💰", "money bag fric"),
        E("💳", "credit card carte"),
        E("💎", "gem diamant"),
        E("⚖️", "balance justice"),
        E("🪜", "ladder echelle"),
        E("🧰", "toolbox"),
        E("🪛", "screwdriver tournevis"),
        E("🔧", "wrench cle"),
        E("🔨", "hammer marteau"),
        E("⚒️", "hammer pick"),
        E("🛠️", "hammer wrench"),
        E("⛏️", "pick pioche"),
        E("🪚", "saw scie"),
        E("🔩", "nut bolt vis"),
        E("⚙️", "gear engrenage"),
        E("🪤", "mouse trap"),
        E("🧱", "brick brique"),
        E("⛓️", "chains chaines"),
        E("🧲", "magnet aimant"),
        E("🔫", "pistol eau"),
        E("💣", "bomb bombe"),
        E("🧨", "firecracker petard"),
        E("🪓", "axe hache"),
        E("🔪", "kitchen knife couteau"),
        E("🗡️", "dagger"),
        E("⚔️", "swords epees"),
        E("🛡️", "shield bouclier"),
        E("🚬", "cigarette"),
        E("⚰️", "coffin cercueil"),
        E("🪦", "headstone tombe"),
        E("⚱️", "urn urne"),
        E("🏺", "amphora"),
        E("🔮", "crystal ball"),
        E("📿", "prayer beads"),
        E("🧿", "nazar amulet"),
        E("💈", "barber"),
        E("⚗️", "alembic"),
        E("🔭", "telescope"),
        E("🔬", "microscope"),
        E("🕳️", "hole"),
        E("🩹", "bandage pansement"),
        E("🩺", "stethoscope"),
        E("💊", "pill comprime"),
        E("💉", "syringe piqure"),
        E("🩸", "drop of blood sang"),
        E("🧬", "dna adn"),
        E("🦠", "microbe virus"),
        E("🧫", "petri dish"),
        E("🧪", "test tube"),
        E("🌡️", "thermometer"),
        E("🧹", "broom balai"),
        E("🪠", "plunger"),
        E("🧺", "basket panier"),
        E("🧻", "roll of paper pq"),
        E("🚽", "toilet wc"),
        E("🚰", "potable water"),
        E("🚿", "shower douche"),
        E("🛁", "bathtub baignoire"),
        E("🛀", "bath"),
        E("🧼", "soap savon"),
        E("🪥", "toothbrush brosse"),
        E("🪒", "razor rasoir"),
        E("🧽", "sponge eponge"),
        E("🧴", "lotion bottle"),
        E("🛎️", "bellhop bell"),
        E("🔑", "key cle"),
        E("🗝️", "old key"),
        E("🚪", "door porte"),
        E("🪑", "chair chaise"),
        E("🛋️", "couch canape"),
        E("🛏️", "bed lit"),
        E("🛌", "person bed"),
        E("🧸", "teddy ours"),
        E("🪆", "nesting dolls"),
        E("🖼️", "framed picture cadre"),
        E("🪞", "mirror miroir"),
        E("🪟", "window fenetre"),
        E("🛍️", "shopping bags"),
        E("🛒", "cart caddie"),
        E("🎁", "gift cadeau"),
        E("🎈", "balloon ballon"),
        E("🎏", "carp streamer"),
        E("🎀", "ribbon noeud"),
        E("🪄", "magic wand baguette"),
        E("🪅", "pinata"),
        E("🎊", "confetti"),
        E("🎉", "party popper fetard"),
        E("🎎", "dolls"),
        E("🏮", "red lantern"),
        E("🎐", "wind chime"),
        E("🧧", "red envelope"),
        E("✉️", "envelope enveloppe"),
        E("📩", "envelope arrow"),
        E("📨", "incoming envelope"),
        E("📧", "e-mail mail"),
        E("💌", "love letter"),
        E("📥", "inbox"),
        E("📤", "outbox"),
        E("📦", "package colis"),
        E("🏷️", "label etiquette"),
        E("🪧", "placard pancarte"),
        E("📪", "mailbox closed"),
        E("📫", "mailbox"),
        E("📬", "mailbox open"),
        E("📭", "mailbox lowered"),
        E("📮", "postbox"),
        E("📯", "postal horn"),
        E("📜", "scroll parchemin"),
        E("📃", "page curl"),
        E("📄", "page facing"),
        E("📑", "bookmark tabs"),
        E("🧾", "receipt recu"),
        E("📊", "bar chart stats"),
        E("📈", "chart up"),
        E("📉", "chart down"),
        E("🗒️", "notepad"),
        E("🗓️", "spiral calendar"),
        E("📆", "tear-off calendar"),
        E("📅", "calendar calendrier"),
        E("🗑️", "wastebasket poubelle"),
        E("📇", "card index"),
        E("🗃️", "card file box"),
        E("🗳️", "ballot box vote"),
        E("🗄️", "file cabinet"),
        E("📋", "clipboard presse papiers"),
        E("📁", "file folder dossier"),
        E("📂", "open folder"),
        E("🗂️", "dividers"),
        E("🗞️", "rolled newspaper"),
        E("📰", "newspaper journal"),
        E("📓", "notebook cahier"),
        E("📔", "notebook deco"),
        E("📒", "ledger"),
        E("📕", "closed book livre"),
        E("📗", "green book"),
        E("📘", "blue book"),
        E("📙", "orange book"),
        E("📚", "books livres"),
        E("📖", "open book livre"),
        E("🔖", "bookmark marque page"),
        E("🧷", "safety pin epingle"),
        E("🔗", "link lien"),
        E("📎", "paperclip trombone"),
        E("🖇️", "linked paperclips"),
        E("📐", "triangle ruler"),
        E("📏", "straight ruler"),
        E("🧮", "abacus boulier"),
        E("📌", "pushpin punaise"),
        E("📍", "round pushpin"),
        E("✂️", "scissors ciseaux"),
        E("🖊️", "pen stylo"),
        E("🖋️", "fountain pen"),
        E("✒️", "nib"),
        E("🖌️", "paintbrush pinceau"),
        E("🖍️", "crayon pastel"),
        E("📝", "memo note"),
        E("✏️", "pencil crayon"),
        E("🔍", "search loupe"),
        E("🔎", "search right"),
        E("🔏", "locked pen"),
        E("🔐", "locked key"),
        E("🔒", "locked cadenas"),
        E("🔓", "unlocked"),
    ];

    private static EmojiItem[] Symbols() =>
    [
        E("❤️", "heart coeur rouge love amour"),
        E("🧡", "orange heart"),
        E("💛", "yellow heart"),
        E("💚", "green heart"),
        E("💙", "blue heart"),
        E("💜", "purple heart"),
        E("🖤", "black heart"),
        E("🤍", "white heart"),
        E("🤎", "brown heart"),
        E("💔", "broken heart"),
        E("❣️", "heart exclamation"),
        E("💕", "two hearts"),
        E("💞", "revolving hearts"),
        E("💓", "beating heart"),
        E("💗", "growing heart"),
        E("💖", "sparkling heart"),
        E("💘", "heart arrow"),
        E("💝", "heart ribbon"),
        E("💟", "heart decoration"),
        E("☮️", "peace paix"),
        E("✝️", "cross croix"),
        E("☪️", "star crescent islam"),
        E("🕉️", "om"),
        E("☸️", "wheel of dharma"),
        E("✡️", "star of david"),
        E("🔯", "six pointed star"),
        E("🕎", "menorah"),
        E("☯️", "yin yang"),
        E("☦️", "orthodox cross"),
        E("🛐", "place of worship"),
        E("⛎", "ophiuchus"),
        E("♈", "aries belier"),
        E("♉", "taurus taureau"),
        E("♊", "gemini gemeaux"),
        E("♋", "cancer"),
        E("♌", "leo lion"),
        E("♍", "virgo vierge"),
        E("♎", "libra balance"),
        E("♏", "scorpio scorpion"),
        E("♐", "sagittarius"),
        E("♑", "capricorn"),
        E("♒", "aquarius"),
        E("♓", "pisces poissons"),
        E("🆔", "id"),
        E("⚛️", "atom atome"),
        E("🉑", "accept"),
        E("☢️", "radioactive"),
        E("☣️", "biohazard"),
        E("📴", "phone off"),
        E("📳", "vibration"),
        E("🈶", "not free"),
        E("🈚", "free"),
        E("🈸", "application"),
        E("🈺", "open"),
        E("🈷️", "monthly"),
        E("✴️", "eight pointed star"),
        E("🆚", "vs versus"),
        E("💮", "white flower"),
        E("🉐", "bargain"),
        E("㊙️", "secret"),
        E("㊗️", "congratulations"),
        E("🈴", "passing grade"),
        E("🈵", "no vacancy"),
        E("🈹", "discount"),
        E("🈲", "prohibited"),
        E("🅰️", "a button"),
        E("🅱️", "b button"),
        E("🆎", "ab button"),
        E("🆑", "cl"),
        E("🅾️", "o button"),
        E("🆘", "sos"),
        E("❌", "cross mark croix"),
        E("⭕", "hollow red circle"),
        E("🛑", "stop"),
        E("⛔", "no entry"),
        E("📛", "name badge"),
        E("🚫", "prohibited interdit"),
        E("💯", "hundred 100"),
        E("💢", "anger"),
        E("♨️", "hotsprings"),
        E("🚷", "no pedestrians"),
        E("🚯", "no littering"),
        E("🚳", "no bicycles"),
        E("🚱", "non-potable"),
        E("🔞", "under eighteen"),
        E("📵", "no mobile"),
        E("🚭", "no smoking"),
        E("❗", "exclamation"),
        E("❕", "white exclamation"),
        E("❓", "question"),
        E("❔", "white question"),
        E("‼️", "double exclamation"),
        E("⁉️", "exclamation question"),
        E("🔅", "dim"),
        E("🔆", "bright"),
        E("〽️", "part alternation"),
        E("⚠️", "warning attention"),
        E("🚸", "children crossing"),
        E("🔱", "trident"),
        E("⚜️", "fleur-de-lis"),
        E("🔰", "beginner"),
        E("♻️", "recycle recyclage"),
        E("✅", "check mark vert"),
        E("🈯", "reserved"),
        E("💹", "chart yen"),
        E("❇️", "sparkle"),
        E("✳️", "eight spoked"),
        E("❎", "cross mark button"),
        E("🌐", "globe meridians"),
        E("💠", "diamond dot"),
        E("Ⓜ️", "m circled"),
        E("🌀", "cyclone"),
        E("💤", "zzz"),
        E("🏧", "atm"),
        E("🚾", "wc toilet"),
        E("♿", "wheelchair pmr"),
        E("🅿️", "parking"),
        E("🛗", "elevator ascenseur"),
        E("🛂", "passport control"),
        E("🛃", "customs douane"),
        E("🛄", "baggage claim"),
        E("🛅", "left luggage"),
        E("🚹", "mens"),
        E("🚺", "womens"),
        E("🚼", "baby symbol"),
        E("🚻", "restroom"),
        E("🚮", "litter bin"),
        E("🎦", "cinema"),
        E("📶", "signal antenna"),
        E("🈁", "here"),
        E("🔣", "symbols symboles"),
        E("ℹ️", "information info"),
        E("🔤", "abc"),
        E("🔡", "abcd"),
        E("🔠", "abcd caps"),
        E("🆖", "ng"),
        E("🆗", "ok"),
        E("🆙", "up"),
        E("🆒", "cool"),
        E("🆕", "new nouveau"),
        E("🆓", "free"),
        E("0️⃣", "zero 0"),
        E("1️⃣", "one 1"),
        E("2️⃣", "two 2"),
        E("3️⃣", "three 3"),
        E("4️⃣", "four 4"),
        E("5️⃣", "five 5"),
        E("6️⃣", "six 6"),
        E("7️⃣", "seven 7"),
        E("8️⃣", "eight 8"),
        E("9️⃣", "nine 9"),
        E("🔟", "ten 10"),
        E("🔢", "1234 numbers"),
        E("#️⃣", "hash diese"),
        E("*️⃣", "asterisk"),
        E("⏏️", "eject"),
        E("▶️", "play lecture"),
        E("⏸️", "pause"),
        E("⏯️", "play pause"),
        E("⏹️", "stop"),
        E("⏺️", "record"),
        E("⏭️", "next track"),
        E("⏮️", "last track"),
        E("⏩", "fast forward"),
        E("⏪", "rewind"),
        E("⏫", "fast up"),
        E("⏬", "fast down"),
        E("◀️", "reverse"),
        E("🔼", "up button"),
        E("🔽", "down button"),
        E("➡️", "right arrow droite"),
        E("⬅️", "left arrow gauche"),
        E("⬆️", "up arrow haut"),
        E("⬇️", "down arrow bas"),
        E("↗️", "up-right"),
        E("↘️", "down-right"),
        E("↙️", "down-left"),
        E("↖️", "up-left"),
        E("↕️", "up-down"),
        E("↔️", "left-right"),
        E("↪️", "left arrow hook"),
        E("↩️", "right arrow hook"),
        E("⤴️", "right arrow curving up"),
        E("⤵️", "right arrow curving down"),
        E("🔀", "shuffle"),
        E("🔁", "repeat"),
        E("🔂", "repeat one"),
        E("🔄", "arrows counterclockwise"),
        E("🔃", "arrows clockwise"),
        E("🎵", "note musique"),
        E("🎶", "notes musique"),
        E("➕", "plus"),
        E("➖", "minus"),
        E("➗", "divide"),
        E("✖️", "multiply"),
        E("♾️", "infinity infini"),
        E("💲", "dollar sign"),
        E("💱", "currency"),
        E("™️", "tm marque"),
        E("©️", "copyright"),
        E("®️", "registered"),
        E("〰️", "wavy dash"),
        E("➰", "curly loop"),
        E("➿", "double curly loop"),
        E("✔️", "check coche"),
        E("☑️", "check box"),
        E("🔘", "radio button"),
        E("🔴", "red circle rouge"),
        E("🟠", "orange circle"),
        E("🟡", "yellow circle"),
        E("🟢", "green circle"),
        E("🔵", "blue circle"),
        E("🟣", "purple circle"),
        E("⚫", "black circle"),
        E("⚪", "white circle"),
        E("🟤", "brown circle"),
        E("🔺", "red triangle up"),
        E("🔻", "red triangle down"),
        E("🔸", "small orange diamond"),
        E("🔹", "small blue diamond"),
        E("🔶", "large orange diamond"),
        E("🔷", "large blue diamond"),
        E("🔳", "white square button"),
        E("🔲", "black square button"),
        E("▪️", "black small square"),
        E("▫️", "white small square"),
        E("◾", "black medium small square"),
        E("◽", "white medium small square"),
        E("◼️", "black medium square"),
        E("◻️", "white medium square"),
        E("⬛", "black large square"),
        E("⬜", "white large square"),
        E("🟥", "red square"),
        E("🟧", "orange square"),
        E("🟨", "yellow square"),
        E("🟩", "green square"),
        E("🟦", "blue square"),
        E("🟪", "purple square"),
        E("🟫", "brown square"),
        E("🔈", "speaker low"),
        E("🔇", "muted"),
        E("🔉", "speaker medium"),
        E("🔊", "speaker high"),
        E("🔔", "bell cloche"),
        E("🔕", "bell slash"),
        E("📣", "megaphone"),
        E("📢", "loudspeaker"),
        E("🗨️", "left speech"),
        E("👁️‍🗨️", "eye speech"),
        E("💬", "speech balloon"),
        E("💭", "thought balloon"),
        E("🗯️", "right anger"),
        E("♠️", "spade pique"),
        E("♣️", "club trefle"),
        E("♥️", "heart card coeur"),
        E("♦️", "diamond carreau"),
        E("🃏", "joker"),
        E("🎴", "flower cards"),
        E("🀄", "mahjong"),
        E("🕐", "one oclock heure"),
        E("🕑", "two oclock"),
        E("🕒", "three oclock"),
        E("🕓", "four oclock"),
        E("🕔", "five oclock"),
        E("🕕", "six oclock"),
        E("🕖", "seven oclock"),
        E("🕗", "eight oclock"),
        E("🕘", "nine oclock"),
        E("🕙", "ten oclock"),
        E("🕚", "eleven oclock"),
        E("🕛", "twelve oclock midi minuit"),
    ];

    private static EmojiItem[] Flags() =>
    [
        E("🏳️", "white flag blanc"),
        E("🏴", "black flag noir"),
        E("🏁", "chequered flag course"),
        E("🚩", "triangular flag"),
        E("🏳️‍🌈", "rainbow flag pride lgbt"),
        E("🏳️‍⚧️", "transgender flag trans"),
        E("🏴‍☠️", "pirate flag pirate"),
        E("🇺🇳", "united nations onu"),
        E("🇪🇺", "european union europe ue"),
        E("🇫🇷", "france french francais fr"),
        E("🇧🇪", "belgium belgique be"),
        E("🇨🇭", "switzerland suisse ch"),
        E("🇨🇦", "canada ca"),
        E("🇬🇧", "united kingdom uk gb britain"),
        E("🇺🇸", "united states usa america us"),
        E("🇩🇪", "germany allemagne de"),
        E("🇪🇸", "spain espagne es"),
        E("🇮🇹", "italy italie it"),
        E("🇵🇹", "portugal pt"),
        E("🇳🇱", "netherlands pays bas nl"),
        E("🇱🇺", "luxembourg lu"),
        E("🇮🇪", "ireland irlande ie"),
        E("🇦🇹", "austria autriche at"),
        E("🇵🇱", "poland pologne pl"),
        E("🇸🇪", "sweden suede se"),
        E("🇳🇴", "norway norvege no"),
        E("🇩🇰", "denmark danemark dk"),
        E("🇫🇮", "finland finlande fi"),
        E("🇬🇷", "greece grece gr"),
        E("🇹🇷", "turkey turquie tr"),
        E("🇲🇦", "morocco maroc ma"),
        E("🇩🇿", "algeria algerie dz"),
        E("🇹🇳", "tunisia tunisie tn"),
        E("🇸🇳", "senegal sn"),
        E("🇨🇮", "ivory coast cote ivoire ci"),
        E("🇨🇲", "cameroon cameroun cm"),
        E("🇯🇵", "japan japon jp"),
        E("🇨🇳", "china chine cn"),
        E("🇰🇷", "south korea coree kr"),
        E("🇮🇳", "india inde in"),
        E("🇧🇷", "brazil bresil br"),
        E("🇲🇽", "mexico mexique mx"),
        E("🇦🇷", "argentina argentine ar"),
        E("🇦🇺", "australia australie au"),
        E("🇳🇿", "new zealand nouvelle zelande nz"),
        E("🇷🇺", "russia russie ru"),
        E("🇺🇦", "ukraine ua"),
        E("🇮🇱", "israel il"),
        E("🇸🇦", "saudi arabia arabie sa"),
        E("🇦🇪", "united arab emirates emirats ae"),
        E("🇪🇬", "egypt egypte eg"),
        E("🇿🇦", "south africa afrique du sud za"),
        E("🇳🇬", "nigeria ng"),
    ];
}
